export {default as getPosts} from './getPosts';
export {default as getRecentPosts} from './getRecentPosts';
export {default as getCategories} from './getCategories';
export {default as getPostDetails} from './getPostDetails';
export {default as getComments} from './getComments';
export {default as getSimilarPosts} from './getSimilarPosts';
export {default as submitComment} from './submitComment';
export {default as getFeaturedPosts} from './getFeaturedPosts';
export {default as getCategoryPost} from './getCategoryPost';